# Generated by Django 4.2.7 on 2023-11-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cat_indoor',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='e_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
    ]
